# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Create config.json file
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "config.json"
        json: ${{ secrets.CONFIG_JSON }}
    - name: Create config.json file
      id: create-public-key-file
      uses: 1arp/create-a-file-action@0.3
      with:
        file: 'publicKey.pem'
        content: ${{ secrets.PUBLIC_KEY }}
    - name: Create config.json file
      id: create-private-key-file
      uses: 1arp/create-a-file-action@0.3
      with:
        file: 'privateKey.pem'
        content: ${{ secrets.PRIVATE_KEY }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
